name: Feisal Adur
markdown: redcarpet
highlighter: true
timezone: Europe/Copenhagen
permalink: pretty
baseurl: ''
paginate: 10
domain: 'http://feisal.dk'
github_username: fadur
twitter_username: fadur
instagram_username: fadur
gems: [jekyll-paginate]
author: fadur
title: Feisal Adur
header-img: 'img/home-bg.jpg'
meta-description: Home of Feisal Adur a developer  
page-subtitle: 

